version: '3.8'

services:
  app:
    build: .
    container_name: desafio_php_app
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: desafio_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: desafio
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
